version: '3'

services:

  app:
    build: .
    image: interactive-maapping:dev
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgres
    command: wait-for-it postgres:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/app

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgres:
